// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import PrelineScriptWrapper from "./components/PrelineScriptWrapper";
import SplashScreenWrapper from "./components/SplashScreenWrapper";

// Google Fonts (例: Inter と Roboto Mono)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon/favicon.svg" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="K-Tech" />
        <link rel="manifest" href="/favicon/site.webmanifest" />
      </head>
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {/* コンテンツの上に SplashScreenWrapper でラップ */}
        <SplashScreenWrapper>
          {children}
        </SplashScreenWrapper>
        {/* スクリプトも body 内に配置 */}
        <PrelineScriptWrapper />
      </body>
    </html>
  );
}