// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import PrelineScriptWrapper from "./components/PrelineScriptWrapper";
import SplashScreenWrapper from "./components/SplashScreenWrapper";

// Google Fonts (例: Inter と Roboto Mono)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        {/* コンテンツの上に SplashScreenWrapper でラップ */}
        <SplashScreenWrapper>
          {children}
        </SplashScreenWrapper>
        {/* スクリプトも body 内に配置 */}
        <PrelineScriptWrapper />
      </body>
    </html>
  );
}
